const allIngredients = [
   "Cheese",
  "Lettuce",
  "Tomatoes",
  "Cliantro",
  "Beyond Beef",
  "Lime Crema",
  "Carne Asada",
  "Avocado",
  "Salsa",
  "Shrimp",
  "Slaws Dressing",
  "Chicken",
  "Pico de Gallo",
  "Onions",
  "Avocado",
  "Pork Al Pastor",
  "Fish",
  "Jalepeños",
  "Mango",
  "Beef",
  "Bacon",
  "Salsa",
  "Peppers",
  "Strawberries",
  "Vanilla Ice Cream",
  "Chocolate Sprinkles",
  "Cinnamon Sugar Dipped Graham Crumb Tortilla",
  "Cherry Pie Filling",
  "Cheese Cake",
  "Whipped Cream",

];

export default allIngredients;
